<a href="https://colab.research.google.com/github/lakshmigojanece/project-1/blob/main/earthquake_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



#Earthquake Data

In [ ]:
#Project Title:Global Seismic Trends: Data-Driven Earthquake Insights.

In [ ]:
import requests
import pandas as pd
from datetime import datetime

In [ ]:
url = "https://earthquake.usgs.gov/fdsnws/event/1/query"

In [ ]:
earthquake = []

In [ ]:
# Fixed years: 2020 → 2025
start_year = 2020
end_year = 2025

In [ ]:



for year in range(start_year, end_year + 1):
    for month in range(1, 13):

        start_date = f"{year}-{month:02d}-01"

        if month == 12:
            end_date = f"{year + 1}-01-01"
        else:
            end_date = f"{year}-{month + 1:02d}-01"

        print(f"Fetching {start_date} → {end_date}")

        params = {
            "format": "geojson",
            "starttime": start_date,
            "endtime": end_date,
            "minmagnitude": 3,
            "limit": 20000    # max allowed by USGS
        }

        try:
            response = requests.get(url, params=params)
            data = response.json()
        except Exception:
            print(" JSON decode error. Response:")
            print(response.text[:500])
            continue  # skip to next month



        events = data.get("features", [])

        for eq in events:
            props = eq["properties"]
            geo = eq["geometry"]

            earthquake.append({
                "id": eq.get("id"),
                "time": props.get("time"),
                "updated": props.get("updated"),
                "latitude": geo["coordinates"][1],
                "longitude": geo["coordinates"][0],
                "depth_km": geo["coordinates"][2],
                "mag": props.get("mag"),
                "magType": props.get("magType"),
                "place": props.get("place"),
                "status": props.get("status"),
                "tsunami": props.get("tsunami"),
                "sig": props.get("sig"),
                "net": props.get("net"),
                "nst": props.get("nst"),
                "dmin": props.get("dmin"),
                "rms": props.get("rms"),
                "gap": props.get("gap"),
                "magError": props.get("magError"),
                "depthError": props.get("depthError"),
                "magNst": props.get("magNst"),
                "locationsource": props.get("locationSource"),
                "magsource": props.get("magSource"),
                "types": props.get("types"),
                "ids": props.get("ids"),
                "sources": props.get("sources"),
                "type": props.get("type")
            })

# Convert to DataFrame
df = pd.DataFrame(earthquake)

# Convert timestamps (milliseconds → datetime)
df["time"] = pd.to_datetime(df["time"], unit="ms")
df["updated"] = pd.to_datetime(df["updated"], unit="ms")

Fetching 2020-01-01 → 2020-02-01
Fetching 2020-02-01 → 2020-03-01
Fetching 2020-03-01 → 2020-04-01
Fetching 2020-04-01 → 2020-05-01
Fetching 2020-05-01 → 2020-06-01
Fetching 2020-06-01 → 2020-07-01
Fetching 2020-07-01 → 2020-08-01
Fetching 2020-08-01 → 2020-09-01
Fetching 2020-09-01 → 2020-10-01
Fetching 2020-10-01 → 2020-11-01
Fetching 2020-11-01 → 2020-12-01
Fetching 2020-12-01 → 2021-01-01
Fetching 2021-01-01 → 2021-02-01
Fetching 2021-02-01 → 2021-03-01
Fetching 2021-03-01 → 2021-04-01
Fetching 2021-04-01 → 2021-05-01
Fetching 2021-05-01 → 2021-06-01
Fetching 2021-06-01 → 2021-07-01
Fetching 2021-07-01 → 2021-08-01
Fetching 2021-08-01 → 2021-09-01
Fetching 2021-09-01 → 2021-10-01
Fetching 2021-10-01 → 2021-11-01
Fetching 2021-11-01 → 2021-12-01
Fetching 2021-12-01 → 2022-01-01
Fetching 2022-01-01 → 2022-02-01
Fetching 2022-02-01 → 2022-03-01
Fetching 2022-03-01 → 2022-04-01
Fetching 2022-04-01 → 2022-05-01
Fetching 2022-05-01 → 2022-06-01
Fetching 2022-06-01 → 2022-07-01
Fetching 2022-07-01 → 2022-08-01
Fetching 2022-08-01 → 2022-09-01
Fetching 2022-09-01 → 2022-10-01
Fetching 2022-10-01 → 2022-11-01
Fetching 2022-11-01 → 2022-12-01
Fetching 2022-12-01 → 2023-01-01
Fetching 2023-01-01 → 2023-02-01
Fetching 2023-02-01 → 2023-03-01
Fetching 2023-03-01 → 2023-04-01
Fetching 2023-04-01 → 2023-05-01
Fetching 2023-05-01 → 2023-06-01
Fetching 2023-06-01 → 2023-07-01
Fetching 2023-07-01 → 2023-08-01
Fetching 2023-08-01 → 2023-09-01
Fetching 2023-09-01 → 2023-10-01
Fetching 2023-10-01 → 2023-11-01
Fetching 2023-11-01 → 2023-12-01
Fetching 2023-12-01 → 2024-01-01
Fetching 2024-01-01 → 2024-02-01
Fetching 2024-02-01 → 2024-03-01
Fetching 2024-03-01 → 2024-04-01
Fetching 2024-04-01 → 2024-05-01
Fetching 2024-05-01 → 2024-06-01
Fetching 2024-06-01 → 2024-07-01
Fetching 2024-07-01 → 2024-08-01
Fetching 2024-08-01 → 2024-09-01
Fetching 2024-09-01 → 2024-10-01
Fetching 2024-10-01 → 2024-11-01
Fetching 2024-11-01 → 2024-12-01
Fetching 2024-12-01 → 2025-01-01
Fetching 2025-01-01 → 2025-02-01
Fetching 2025-02-01 → 2025-03-01
Fetching 2025-03-01 → 2025-04-01
Fetching 2025-04-01 → 2025-05-01
Fetching 2025-05-01 → 2025-06-01
Fetching 2025-06-01 → 2025-07-01
Fetching 2025-07-01 → 2025-08-01
Fetching 2025-08-01 → 2025-09-01
Fetching 2025-09-01 → 2025-10-01
Fetching 2025-10-01 → 2025-11-01
Fetching 2025-11-01 → 2025-12-01
Fetching 2025-12-01 → 2026-01-01

In [ ]:
print("--------------------------------------------")

print(df.head())

--------------------------------------------
             id                    time                 updated  latitude  \
0  pr2020031037 2020-01-31 23:42:29.870 2020-04-18 22:10:07.040   18.8990
1    us60007lub 2020-01-31 23:32:51.609 2020-04-18 22:10:07.040   38.4961
2    us60007lul 2020-01-31 23:06:11.255 2020-04-18 22:10:07.040  -12.2747
3    us60007lsc 2020-01-31 22:10:55.844 2025-12-22 18:27:38.231   -6.4065
4    us60007lq0 2020-01-31 21:05:32.436 2020-04-18 22:10:06.040   41.4433

   longitude  depth_km  mag magType  \
0   -67.8238     10.00  3.2      md
1    39.3382     10.00  4.7     mwr
2   -76.6148     75.51  4.7      mb
3   129.1523    221.39  5.0     mww
4    19.4321     10.00  4.4      mb

                                         place    status  ...    gap  \
0  70 km ENE of Punta Cana, Dominican Republic  reviewed  ...  321.0
1                  6 km NNE of Sivrice, Turkey  reviewed  ...   34.0
2               21 km ENE of San Bartolo, Peru  reviewed  ...  167.0
3                                    Banda Sea  reviewed  ...   28.0
4                   13 km N of Durrës, Albania  reviewed  ...   51.0

   magError depthError  magNst  locationsource  magsource  \
0      None       None    None            None       None
1      None       None    None            None       None
2      None       None    None            None       None
3      None       None    None            None       None
4      None       None    None            None       None

                                    types                           ids  \
0                ,dyfi,origin,phase-data,     ,pr2020031037,us60007lv7,
1       ,moment-tensor,origin,phase-data,                  ,us60007lub,
2                ,dyfi,origin,phase-data,                  ,us60007lul,
3  ,dyfi,moment-tensor,origin,phase-data,  ,us60007lsc,iscgem617252948,
4                     ,origin,phase-data,                  ,us60007lq0,

       sources        type
0      ,pr,us,  earthquake
1         ,us,  earthquake
2         ,us,  earthquake
3  ,us,iscgem,  earthquake
4         ,us,  earthquake

[5 rows x 26 columns]

In [ ]:
df["id"] = df["id"].astype(str)  # primary key

df["latitude"] = df["latitude"].astype(float)
df["longitude"] = df["longitude"].astype(float)
df["depth_km"] = df["depth_km"].astype(float)
df["mag"] = df["mag"].astype(float)
df["magType"] = df["magType"].astype(str)

In [ ]:
df["place"] = df["place"].astype(str)
df["status"] = df["status"].astype(str)

In [ ]:
df["rms"] = df["rms"].astype(float)
df["gap"] = df["gap"].astype(float)
df["magError"] = df["magError"].astype(float)
df["depthError"] = df["depthError"].astype(float)
df["magNst"] = df["magNst"].astype(float)
df["locationsource"] = df["locationsource"].astype(str)
df["magsource"] = df["magsource"].astype(str)
df["types"] = df["types"].astype(str)
df["ids"] = df["ids"].astype(str)
df["sources"] = df["sources"].astype(str)
df["type"] = df["type"].astype(str)

In [ ]:
df["tsunami"] = df["tsunami"].astype(int)
df["sig"] = df["sig"].astype(int)

In [ ]:
df["net"] = df["net"].astype(str)
df["nst"] = df["nst"].astype(float)
df["dmin"] = df["dmin"].astype(float)

In [ ]:
df

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,gap,magError,depthError,magNst,locationsource,magsource,types,ids,sources,type
0,pr2020031037,2020-01-31 23:42:29.870,2020-04-18 22:10:07.040,18.8990,-67.8238,10.000,3.2,md,"70 km ENE of Punta Cana, Dominican Republic",reviewed,...,321.0,None,None,None,None,None,",dyfi,origin,phase-data,",",pr2020031037,us60007lv7,",",pr,us,",earthquake
1,us60007lub,2020-01-31 23:32:51.609,2020-04-18 22:10:07.040,38.4961,39.3382,10.000,4.7,mwr,"6 km NNE of Sivrice, Turkey",reviewed,...,34.0,None,None,None,None,None,",moment-tensor,origin,phase-data,",",us60007lub,",",us,",earthquake
2,us60007lul,2020-01-31 23:06:11.255,2020-04-18 22:10:07.040,-12.2747,-76.6148,75.510,4.7,mb,"21 km ENE of San Bartolo, Peru",reviewed,...,167.0,None,None,None,None,None,",dyfi,origin,phase-data,",",us60007lul,",",us,",earthquake
3,us60007lsc,2020-01-31 22:10:55.844,2025-12-22 18:27:38.231,-6.4065,129.1523,221.390,5.0,mww,Banda Sea,reviewed,...,28.0,None,None,None,None,None,",dyfi,moment-tensor,origin,phase-data,",",us60007lsc,iscgem617252948,",",us,iscgem,",earthquake
4,us60007lq0,2020-01-31 21:05:32.436,2020-04-18 22:10:06.040,41.4433,19.4321,10.000,4.4,mb,"13 km N of Durrës, Albania",reviewed,...,51.0,None,None,None,None,None,",origin,phase-data,",",us60007lq0,",",us,",earthquake
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124914,ak2025xpgfse,2025-12-01 01:51:06.974,2026-02-25 16:18:40.040,59.1380,-150.6400,15.200,3.2,ml,"60 km SSE of Halibut Cove, Alaska",reviewed,...,149.0,None,None,None,None,None,",origin,phase-data,",",us7000ret4,ak2025xpgfse,",",us,ak,",earthquake
124915,us7000ret3,2025-12-01 01:41:43.796,2026-02-25 16:18:40.040,7.4127,127.0704,35.000,4.6,mb,"53 km E of Baculin, Philippines",reviewed,...,96.0,None,None,None,None,None,",origin,phase-data,",",us7000ret3,",",us,",earthquake
124916,us7000ret2,2025-12-01 01:37:57.834,2026-02-25 16:18:40.040,-19.4176,-67.2761,227.844,4.1,mb,"78 km SW of Challapata, Bolivia",reviewed,...,95.0,None,None,None,None,None,",origin,phase-data,",",us7000ret2,",",us,",earthquake
124917,us7000resz,2025-12-01 01:25:46.725,2026-02-25 16:18:40.040,47.3283,-113.2019,30.159,3.1,ml,"27 km NE of Seeley Lake, Montana",reviewed,...,45.0,None,None,None,None,None,",origin,phase-data,",",us7000resz,",",us,",earthquake
124918,us7000resx,2025-12-01 00:48:01.683,2026-02-25 16:18:40.040,42.0602,142.5913,57.662,4.6,mb,"19 km WSW of Urakawa, Japan",reviewed,...,83.0,None,None,None,None,None,",origin,phase-data,",",us7000resx,",",us,",earthquake

In [ ]:
df.isnull()

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,gap,magError,depthError,magNst,locationsource,magsource,types,ids,sources,type
0,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
505,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,False,False,False,False,False,False
506,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,False,False,False,False,False,False
507,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,False,False,False,False,False,False
508,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,False,False,False,False,False,False
509,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

id                  0
time                0
updated             0
latitude            0
longitude           0
depth_km            0
mag                 0
magType             0
place               0
status              0
tsunami             0
sig                 0
net                 0
nst                 0
dmin                0
rms                 0
gap                 0
magError          510
depthError        510
magNst            510
locationsource      0
magsource           0
types               0
ids                 0
sources             0
type                0
dtype: int64

In [ ]:
df.notnull().sum()

id                510
time              510
updated           510
latitude          510
longitude         510
depth_km          510
mag               510
magType           510
place             510
status            510
tsunami           510
sig               510
net               510
nst               510
dmin              510
rms               510
gap               510
magError            0
depthError          0
magNst              0
locationsource    510
magsource         510
types             510
ids               510
sources           510
type              510
dtype: int64

In [ ]:
df.id.nunique()

123200

In [ ]:
df.id[df.id.duplicated()]

Series([], Name: id, dtype: object)

In [ ]:
df['time'].tail()

123195   2025-12-01 02:22:35.261
123196   2025-12-01 01:51:06.060
123197   2025-12-01 01:41:44.083
123198   2025-12-01 01:37:57.834
123199   2025-12-01 00:48:00.828
Name: time, dtype: datetime64[ns]

In [ ]:
len(df.columns)

26

In [ ]:
len(df)

125435

In [ ]:
pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.44)
Requirement already satisfied: pymysql in /usr/local/lib/python3.12/dist-packages (1.1.2)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

In [ ]:
import libraries
import pandas as Pd
from sqlalchemy import create_engine

ModuleNotFoundError: No module named 'libraries'